Run lsb_release only if the binary is present in the system
steadfasterX/SALT pull request #39
Opened 2023-08-28 05:49 UTC by phodina

2023-08-28 08:03 UTC, steadfasterX approved these changes

2023-08-28 08:05 UTC, steadfasterX requested changes

2023-08-28 08:05 UTC, steadfasterX commented on salt
> +if [ $(which lsb_release 2> /dev/null) ]; then
Please change that to something like:

`which lsb_release > /dev/null 2>&1`

as otherwise you will always get the lsb_release output twice

2023-08-28 13:32 UTC, phodina commented on salt
> +if [ $(which lsb_release 2> /dev/null) ]; then
Fixed

2023-08-31 08:09 UTC, steadfasterX commented on salt
> +if [ $(which lsb_release 2>&1 /dev/null) ]; then
Im sorry but it is missing a redirection now. just do this and it will be fine:

`if [ $(which lsb_release > /dev/null 2>&1) ]; then`

2023-12-08 17:29 UTC, closed without merging